### ISSUE TITLE
indicator-datetime build error

### ISSUE THREAD

**Issue by dsandstrom** [alucryd/aur-alucryd#17] opened 2015-02-14 20:34 UTC
I receive an error when running `makepkg`
```
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands
configure:

Date and Time Indicator Configuration:

	Prefix:        /usr
	Indicator Dir: /usr/lib/indicators3/7/
	CC Panel:      no
	CC Panel Dir:  
	systemd:       yes
	gcov:          no

make  all-recursive
make[1]: Entering directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2'
Making all in src
make[2]: Entering directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2/src'
make  all-am
make[3]: Entering directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2/src'
  CC       libdatetime_la-utils.lo
utils.c:35:23: fatal error: timedated.h: No such file or directory
 #include "timedated.h"
                       ^
compilation terminated.
Makefile:722: recipe for target 'libdatetime_la-utils.lo' failed
make[3]: *** [libdatetime_la-utils.lo] Error 1
make[3]: Leaving directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2/src'
Makefile:518: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2/src'
Makefile:472: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-drail/aur-indicator-datetime/src/indicator-datetime-12.10.2'
Makefile:403: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build indicator-datetime.

```

**Comment by alucryd** [comment] 2015-02-18 10:59
It happens here from time to time, I haven't pinpointed the cause yet, building in a clean chroot seems to work fine. You can get it pre-built from my nightly pantheon repo anyway, see https://wiki.archlinux.org/index.php/Pantheon#Installation

**Comment by alucryd** [comment] 2015-05-19 07:36
Should be fixed now.

**Closed by alucryd** 2015-05-19 07:36 UTC
